version: '{branch}.{build}'
clone_folder: c:\projects\pocketmine_chunkutils

environment:
  PHP_SDK_BINARY_TOOLS_VER: php-sdk-2.0.10
  ARCH: x64

  matrix:
    - PHP_VER: 7.0
      VC_VER: vc14
    - PHP_VER: 7.2
      VC_VER: vc15
install:
- cmd: cinst wget
build_script:
- cmd: >-
    "C:\projects\pocketmine_chunkutils\appveyor\build.bat"

test_script:
- cmd: C:\projects\pocketmine_chunkutils\bin\php.exe -doutput_buffering=0 run-tests.php ext\pocketmine_chunkutils -p C:\projects\pocketmine_chunkutils\bin\php.exe -q --show-diff
artifacts:
  - path: bin\ext
    name: php_pocketmine_chunkutils-%PHP_VER%-%VC_VER%-%ARCH%
    type: zip
